### ISSUE TITLE
IndicatorsControl Navigation Issue

### ISSUE THREAD

**Issue by mikkdev** [AndreiMisiukevich/CardView.MAUI#38] opened 2024-10-18 08:43 UTC
**Description:**
When either IsPrevItemPanInteractionEnabled or IsNextItemPanInteractionEnabled is set to false, the expectation is that navigation to previous or next items should be disabled. However, even with these properties set to false, it is still possible to navigate through the IndicatorsControl , which should not be allowed.

This behavior contradicts the intended design of disabling user navigation when pan interaction is turned off.

Steps to Reproduce:

- Set up a project using the CardView control with an associated IndicatorsControl.
- In the properties of CardView, set:
IsPrevItemPanInteractionEnabled = false
OR/AND IsNextItemPanInteractionEnabled = false
- Try to swipe or pan to the next or previous items (as expected, panning is disabled).
- Attempt navigation using the IndicatorView (the navigation remains possible, which is unintended).

_.net MAUI (.net 8) Android_

**Comment by DashTheDev** [comment] 2024-10-18 09:04
Hey @mikkdev! Have you tried setting `IsTapToNavigateEnabled = false;` on the `IndicatorsControl`? That should work for you, if it doesn't let me know.

The way I read `IsPrevItemPanInteractionEnabled` and `IsNextItemPanInteractionEnabled` is that they are explicitly referring to the `Pan` event, due to the `PanInteraction` part of the variable name. So, I think that's working as expected as it does prevent the `Pan` event from triggering the previous or next animation. That being said the documentation is pretty vague on the property with the following description 

> Determines wether next items are available for user interaction.

Which can be interpreted the way you've described since "user interaction" is a very broad term and could encompass the `ArrowContols` as well as the `IndicatorsControls`. So maybe there's room for improvement here? Whether it be docs, property names, creating more properties to enable/disable previous & next navigation as a whole, etc.

**Comment by mikkdev** [comment] 2024-10-18 13:29
@DashTheDev My **workaround** solution is to delete the IndicatorsControl and create an IndicatorView and define a custom IndicatorTemplate (or DataTemplate) for it. Within this template, I’ve created a Border element. The key aspect of my implementation is that I bind the InputTransparent property of the Border to a condition using a Binding.

**Comment by DashTheDev** [comment] 2024-10-18 16:38
Okay, so just to clarify, setting 'IsTapToNavigateEnabled = false;' on the 'IndictaorsControl' didn't work for you then?

With the sample I was able to achieve the required functionality both with a custom template and without when the property was set or bound to false. So if that's not working for you then there's something specific to your implementation that we'll have to explore.

**Comment by AndreiMisiukevich** [comment] 2024-10-21 20:42
Hello, thanks for the question.

This is not a bug. The props you are referring to control PAN interaction (card sliding with a finger, mouse cursor). This doesn't limit you to navigating from code, for example.

But I agree that there is a backdoor with IndicatorsControl... which could be covered by `IsTapToNavigateEnabled`.

Essentially, like @DashTheDev said `IsTapToNavigateEnabled="False"` will prevent navigation by clicking indicators.

**Comment by AndreiMisiukevich** [comment] 2024-10-21 20:43
I am closing this issue as resolved unless more info is provided (then feel free to reopen it, we will help to figure out with that).

**Closed by AndreiMisiukevich** 2024-10-21 20:43 UTC
